server:
  port: 5001

spring:
  # 服务器
  application:
    name: visualization-auth

  # nacos注册
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #数据库驱动配置信息
  datasource:
    #mysql数据源
    url: jdbc:mysql://localhost:3306/visualization-auth?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    #数据源其他配置
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 每6秒运行一次空闲连接回收器 / 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 6000
    # 池中的连接空闲10s后被回收/配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis:  10000
    # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: truek
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=300

  #Jpa配置
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

secure:
  ignore:
    urls:
      - "/actuator/**"
      - "/auth/oauth/token"
      - "/api-docs"
      - "/swagger-ui.html"
      - "/swagger-resources/**"
      - "/swagger-resources"
      - "/v2/api-docs"
      - "/swagger-resources/configuration/ui"
      - "/**/springfox-swagger-ui/**"

management:
  endpoints:
    web:
      exposure:
        include: "*"


